import doctorFemaleImg from "../assets/doctor-female.png";
import doctorMaleImg from "../assets/doctor-male.png";

export const mockDoctors = [
  {
    id: 1,
    name: "Dr. Arman Hossain",
    specialty: "Cardiologist",
    experience: "10+ Years Exp.",
    experienceYears: 10,
    image: doctorMaleImg,
    rating: 4.9,
    reviews: 120,
    fee: "৳700",
    feeAmount: 700,
  },
  {
    id: 2,
    name: "Dr. Nusrat Jahan",
    specialty: "Dermatologist",
    experience: "8+ Years Exp.",
    experienceYears: 8,
    image: doctorFemaleImg,
    rating: 4.8,
    reviews: 98,
    fee: "৳600",
    feeAmount: 600,
  },
  {
    id: 3,
    name: "Dr. Rifat Hasan",
    specialty: "Neurologist",
    experience: "12+ Years Exp.",
    experienceYears: 12,
    image: doctorMaleImg,
    rating: 4.9,
    reviews: 150,
    fee: "৳800",
    feeAmount: 800,
  },
  {
    id: 4,
    name: "Dr. Farhana Islam",
    specialty: "Pediatrician",
    experience: "6+ Years Exp.",
    experienceYears: 6,
    image: doctorFemaleImg,
    rating: 4.7,
    reviews: 85,
    fee: "৳500",
    feeAmount: 500,
  },
  {
    id: 5,
    name: "Dr. Kamal Ahmed",
    specialty: "Orthopedic",
    experience: "15+ Years Exp.",
    experienceYears: 15,
    image: doctorMaleImg,
    rating: 4.6,
    reviews: 210,
    fee: "৳1000",
    feeAmount: 1000,
  },
  {
    id: 6,
    name: "Dr. Sadia Rahman",
    specialty: "Gynecologist",
    experience: "9+ Years Exp.",
    experienceYears: 9,
    image: doctorFemaleImg,
    rating: 4.9,
    reviews: 180,
    fee: "৳700",
    feeAmount: 700,
  },
  {
    id: 7,
    name: "Dr. Tariqul Islam",
    specialty: "Cardiologist",
    experience: "20+ Years Exp.",
    experienceYears: 20,
    image: doctorMaleImg,
    rating: 5.0,
    reviews: 320,
    fee: "৳1200",
    feeAmount: 1200,
  },
  {
    id: 8,
    name: "Dr. Ayesha Siddiqa",
    specialty: "Neurologist",
    experience: "5+ Years Exp.",
    experienceYears: 5,
    image: doctorFemaleImg,
    rating: 4.5,
    reviews: 65,
    fee: "৳500",
    feeAmount: 500,
  },
  {
    id: 9,
    name: "Dr. Mahmudul Hasan",
    specialty: "Dermatologist",
    experience: "11+ Years Exp.",
    experienceYears: 11,
    image: doctorMaleImg,
    rating: 4.8,
    reviews: 140,
    fee: "৳800",
    feeAmount: 800,
  },
  {
    id: 10,
    name: "Dr. Tahmina Akter",
    specialty: "Pediatrician",
    experience: "14+ Years Exp.",
    experienceYears: 14,
    image: doctorFemaleImg,
    rating: 4.9,
    reviews: 250,
    fee: "৳900",
    feeAmount: 900,
  },
  {
    id: 11,
    name: "Dr. Shafiqul Alam",
    specialty: "Orthopedic",
    experience: "7+ Years Exp.",
    experienceYears: 7,
    image: doctorMaleImg,
    rating: 4.4,
    reviews: 90,
    fee: "৳600",
    feeAmount: 600,
  },
  {
    id: 12,
    name: "Dr. Nabila Chowdhury",
    specialty: "Gynecologist",
    experience: "3+ Years Exp.",
    experienceYears: 3,
    image: doctorFemaleImg,
    rating: 4.3,
    reviews: 45,
    fee: "৳400",
    feeAmount: 400,
  }
];
